### ISSUE TITLE
Smartparens support for Elixir

### ISSUE THREAD

**Issue by Fuco1** [elixir-editors/emacs-elixir#389]
Hello friends!

I started working with Elixir recently so naturally I decided to cook up some Elixir support in SP.  I've noticed you have some info in your readme about how to configure it, so I figured you might want to update it.

I'm currently working on the support in this PR: https://github.com/Fuco1/smartparens/pull/695 feel free to get involved, I'm still an Elixir newbie.

You can provide examples where things fail or new feature requests.  I will ship this with the next release and then we can improve things incrementally.

Thanks! :)

**Comment by ckhrysze** [comment]
I wanted smartparens to work with Elixir today, and eventually noticed that piggy backing on sp-ruby was no longer needed. I came here to see about updating the docs, and came across this issue. So first, thank you! Second, I'm happy to create a pull request modifying the README to point this addition to smartparens out, but as I had nothing to do with it, nor have I been involved with this project, wanted to ask if that would be welcome first.

**Comment by Fuco1** [comment]
As a general rule when you open a PR on somebody's project they will get super excited.  It means people care about our work and that always feels good.  So go ahead!

**Comment by Trevoke** [comment]
Smartparens supports Elixir and this is indicated in the README. Closing this issue.

Thanks for bringing support of Elixir to smartparens!
