### ISSUE TITLE
Doesn't Maintain Column When Navigating Up and Down through empty rows when show-paren-mode enabled

### ISSUE THREAD

**Issue by jasongoodwin** [elixir-editors/emacs-elixir#409]
UPDATE Feb2 2018

Disabling `show-paren-mode` corrects the behaviour so this is somehow caused by the intersection of show-paren-mode w/ elixir major mode.

Show paren mode is very useful and otherwise functions correctly in elixir major mode! Would be nice to be able to use this feature without it crippling the ability to edit files.

------

The editor will snap back to 0 column when navigating up and down through empty rows in elixir major mode when returning to a longer row. Only happens in elixir mode. Not sure why/what causes this. I have a fairly minimal configuration in vanilla emacs.

Eg see:

```
defmodule Yo do

end
```

If I go from the `d` in `end` and navigate up two lines (c-p, c-p) I end up on `d` when I expect to end up on `f` or the blank space following it.
If I go to the `o` in `do` on the first line, and I navigate down two lines (c-n, c-n) I end up on `e` on the last line when I expect to end up on`d` or the blank space following it.

If I copy the text into eg org mode or the scratch buffer, it behaves as I expect.

I'm on OSX.

config is here
https://github.com/jasongoodwin/.emacs.d

To reproduce, install vanilla emacs, drop the config in, and open a file with `.ex` or `.exs` extension. 
`GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2016-09-20`

Same is obseved on terminal with the configuration installed in 
```GNU Emacs 25.2.1```

**Comment by gausby** [comment]
I cannot reproduce. I am currently on Emacs 25.3.1 running on macOS.

I suggest trying to upgrade your Emacs.

**Comment by jasongoodwin** [comment]
Will do! I'll let you know. Thanks for looking.

**Comment by jasongoodwin** [comment]
I upgraded to Emacs 25.3.1 and still see the issue unfortunately. I'll try to figure out what's happening.

**Comment by gausby** [comment]
Okay, I took a deeper look at your config and managed to reproduce the issue (I am now on Emacs 26.0.91).

If you disable `show-paren-mode` (M-x show-paren-mode) the problem will go away.

**Comment by jasongoodwin** [comment]
sweet thanks. That's strange - I'll try to learn some more elisp and figure out what interaction causes that. Really appreciate you taking the time to look.

**Comment by jasongoodwin** [comment]
Gonna keep this open and rename it to be more descriptive. 
I would consider this a bug that you can't use show-paren-mode w/ elixir mode.

**Comment by ddovod** [comment]
Hello.
@jasongoodwin Thank you very much for the investigation. I've faced the same issue, the thing is show-paren-mode works fine with all other major modes I use and only elixir-mode interfere with it causing this weird effect. I would reopen the issue and at least wait for somebody to check if this can be fixed in elixir-mode.
