### ISSUE TITLE
Looking for maintainers :)

### ISSUE THREAD

**Issue by josevalim** [elixir-editors/emacs-elixir#410]
If you would like to help maintain this project, please let us know!

/cc @anildigital

**Comment by Trevoke** [comment]
I can help with this. I'll need a little time to get up to speed with the codebase, of course. And since I eventually want to help maintain alchemist, too, might as well get started. Let me know what you'd want to know about me to help you decide.

**Comment by josevalim** [comment]
@Trevoke You have been invited! :heart:

**Comment by Trevoke** [comment]
Alright, I'm in! :)

**Comment by Trevoke** [comment]
Let's maintain this.. Time to review some talks on maintaining both my sanity and the project's.

**Comment by whatyouhide** [comment]
Thanks for stepping up and taking this responsibility @Trevoke, this is incredibly helpful for the health of our community. 💟 💟 💟 💟 💟

**Comment by Trevoke** [comment]
@whatyouhide Thank you! I am glad to be able to help.
