### ISSUE TITLE
Why elixir-format use erl ? SyntaxError error with asdf

### ISSUE THREAD

**Issue by EmilienMottet** [elixir-editors/emacs-elixir#429]
When I run the command ```elixir-format``` 

emacs try to run 
```
erl -pa /usr/lib64/elixir/bin/../lib/eex/ebin /usr/lib64/elixir/bin/../lib/elixir/ebin /usr/lib64/elixir/bin/../lib/ex_unit/ebin /usr/lib64/elixir/bin/../lib/iex/ebin /usr/lib64/elixir/bin/../lib/logger/ebin /usr/lib64/elixir/bin/../lib/mix/ebin -noshell -s elixir start_cli -extra /home/emilien/.asdf/shims/mix format /tmp/elixir-formathBxPhW.ex
```

And so, I have an error with because is not the binary.
errror output :
``` 
** (SyntaxError) /home/emilien/.asdf/shims/mix:3: syntax error before: '.'
    (elixir) lib/code.ex:767: Code.require_file/2
```
/home/emilien/.asdf/shims/mix : 
```
#!/usr/bin/env bash
# asdf-plugin: elixir 1.3.4
exec '/home/emilien/.asdf/bin/asdf exec "mix" "$@"'

```

**Comment by Trevoke** [comment]
Hi, that is strange. Consider recreating the shims? My asdf mix looks like this:

```bash
#!/usr/bin/env elixir
# asdf-plugin: elixir
Mix.start
```

**Comment by EmilienMottet** [comment]
Humm,
I recreate the shims, but I have the same result. 
I don't understand why It's use bash instead of elixir shebang

**Comment by Trevoke** [comment]
maybe upgrade asdf and the elixir plugin?

**Comment by EmilienMottet** [comment]
I use the lastest master for asdf : cf6149f
and the same on elixir plugin : e6f3b15

**Comment by axelson** [comment]
What OS are you on? Does you shim still look the same after you recreated it? It's odd to me that the second line is `# asdf-plugin: elixir 1.3.4` instead of `# asdf-plugin: elixir`

**Comment by EmilienMottet** [comment]
I'm on gentoo, 
I have the same result after reshim.
I manualy update the shim and work well. 
But I don't undestand why I don't I have this shim
