### ISSUE TITLE
Is there a way to auto alias a module defined in the project?

### ISSUE THREAD

**Issue by junjizhi** [elixir-editors/emacs-elixir#430]
If yes, that would be helpful, without typing alias all the time.

**Comment by victorolinasc** [comment]
I don't quite get the kind of functionality you want here. You mean type the fully qualified module name and then calling a function to create the alias?

**Comment by junjizhi** [comment]
Yeah, I was thinking something like below. Image you already have a module with long names:

```elixir
defmodule Foo.Bar.Baz do
  def func(), do: ...
end
```

Now in another file, you want use func. Usually I would type `Baz.func` in the code and forget to alias the module in the file. So the feature is, when the cursor is on `Baz`, have Emacs to match the `Foo.Bar.Baz` module, and auto insert the below line up in the beginning of the module I'm in:

```elixir
alias Foo.Bar.Baz
```

WDYT? @victorolinasc

**Comment by victorolinasc** [comment]
I think this is kinda tricky... it could clash with dependencies and many other things.

I ALSO think this is not the proper place for such functionality. This should go more into elixir-ls or other language servers. I am not aware of how, for example, they are handling project specific `.iex.exs` configuration files.

Will close this for now :)
