### ISSUE TITLE
elixir-format fails with asdf version manager ?

### ISSUE THREAD

**Issue by jeanparpaillon** [elixir-editors/emacs-elixir#431]
Hi,
I'm using emacs 26.1 with elixir-mode (20190319.1844, from ELPA).
My elixir env versioning is managed with asdf (https://github.com/asdf-vm/asdf).

asdf uses shell 'shims' to wrap right version version.

When running `elixir-format` without asdf (PATH does not include asdf shims), everything's fine.
When running `elixir-format` with asdf wrappers, I have the following error:

```
** (SyntaxError) /home/jean/.asdf/shims/mix:4: syntax error before: '.'
    (elixir) lib/code.ex:767: Code.require_file/2
```

When running the command executed by emacs in the terminal, it's fine too:

```
~/.asdf/shims/mix format --dot-formatter /path/to/formatter.exs file-to-format.exs
```

The asdf shim:

```
#!/usr/bin/env bash
# asdf-plugin: elixir 1.7.4
# asdf-plugin: elixir 1.8.1
exec /home/jean/.asdf/bin/asdf exec "mix" "$@"
```

Any idea ?

**Comment by mattmatters** [comment]
Echoing that I also get this error.
So far my investigation has been that elixir is being run against the shim.

**Comment by gabrielelana** [comment]
@mbunkus correct, what follows is my temporary quick & dirty fix

```elisp
(defun elixir-format--from-mix-root (elixir-path errbuff format-arguments)
  "Run mix format where `mix.exs' is located, because mix is
meant to be run from the project root. Otherwise, run in the
current directory."
  (let ((original-default-directory default-directory)
        (mix-dir (locate-dominating-file buffer-file-name "mix.exs")))

    (when mix-dir
      (setq default-directory (expand-file-name mix-dir)))

    (message (concat "Run "
                     (abbreviate-file-name default-directory) ": "
                     (mapconcat 'identity format-arguments " ")))

    (let* ((formatter-executable (car format-arguments))
           (formatter-arguments (cdr format-arguments))
           (result (apply #'call-process
                         formatter-executable nil errbuff nil formatter-arguments)))
      (setq default-directory original-default-directory)
      result)))
```

Basically ignoring `elixir-path` and executing directly `mix`

@anildigital Why run `elixir mix format ...` in the first place? Especially when `mix` has been found with `executable-find` (aka it's supposed to be executable on its own)
