### ISSUE TITLE
Can't type [ while in iex using alchemist..

### ISSUE THREAD

**Issue by donileo** [elixir-editors/emacs-elixir#432]
As the title says when in iex via alchemist I cant type the key `[`. If in that buffer I disable elixir-mode now [ gets processed literally.

**Comment by victorolinasc** [comment]
This repo is not about alchemist and does not have any support for IEx currently (unfortunately). I'm closing this now because of that but feel free to ask questions if still in doubt. 

This will probably need to be opened in Alchemist repo but I think no one is maintaining it currently.
