### ISSUE TITLE
Melpa stable is outdated

### ISSUE THREAD

**Issue by achempion** [elixir-editors/emacs-elixir#434]
I've noticed Melpa stable has the latest release made 3 years ago. Shall we make a new one?

**Comment by victorolinasc** [comment]
Most certainly need to do that :) I'll open a PR about this though the Changelog might be huge...

**Comment by victorolinasc** [comment]
Just released a tag 2.4.0. Should trigger a new build in non-gnu elpa.

**Comment by victorolinasc** [comment]
AND melpa stable kkkk sorry
