### ISSUE TITLE
IEx Mode?

### ISSUE THREAD

**Issue by J3RN** [elixir-editors/emacs-elixir#443]
Hey friends! :wave: I, like many Elixir developers, spend a good deal of time in IEx and want a good Emacs mode to facilitate IEx fiddling.

I did a little digging, and discovered that emacs-elixir _had_ an IEx mode, but it was moved into Alchemist. Unfortunately, though, it appears that the Alchemist project has been dormant for over a year now with no new commits. This project, conversely, appears to still be somewhat active.

Consequently, if someone (me) were to contribute an IEx mode back to this repository, would that change be considered for acceptance?

Thanks! Love the plugin :heart:

**Comment by Trevoke** [comment]
Hello! Connecting iex to lsp is something we'd love to do, we just haven't
dedicated time to it. If you were to contribute something like an inferior
mode that connects to the lsp server, that would be amazing :D

**Comment by axelson** [comment]
@Trevoke Hmmm, I thought that emacs-elixir doesn't depend on lsp? Am I misunderstanding something?

**Comment by Trevoke** [comment]
Ohhhhh I am sorry. That's what I get for trying to communicate when I'm
sleepy. I'm working with both this package and the lsp-elixir community and
I got confused.

Let's pretend this didn't happen. It sounds like it might be a good
addition. Would you please tell me a little more about what you have in
mind?

Depending on purpose / scope, an inferior elixir mode might also be a good
standalone package, like these: https://melpa.org/#/?q=inf-

**Comment by J3RN** [comment]
No worries! :smile:

Actually inf-ruby is similar to what I was thinking of. The IEx mode should contain at least basic functionality such as
- ability to interact with IEx in a shell-type environment
- ability to send code from an Elixir buffer into the IEx shell (e.g. `iex-send-buffer`, `iex-send-region`, `iex-send-line`, etc)

Ideally it should have Mix integration, so as to be able to run `iex -S mix` (and have IEx run alongside mix tasks such as `iex -S mix test` or `iex -S mix phx.server`, etc). That's a bit more nuanced but not terribly difficult since we'd have to navigate to the directory with the `mix.exs` file and start the IEx shell there.

I can start hacking on an `inf-elixir` package and see where that takes me :smile:
