### ISSUE TITLE
Map keys regex crashes/zombifies emacs master

### ISSUE THREAD

**Issue by deadtrickster** [elixir-editors/emacs-elixir#445]
Hi,

when I try open elixir file on emacs master. emacs completely freezes. C-g, ESC nothing can help.
This happened a couple of weeks ago and today I decided to dig into this and found these lines:

```
(,(elixir-rx (group (and (one-or-more identifiers) ":")) space)
     1 elixir-atom-face)
```

If I replace it with

```
(,(elixir-rx (group (and identifiers ":")) space)
     1 elixir-atom-face)
```

everything is ok.

Probably bug in emacs rx module? I'm not sure... Why one-or-more?

Thanks

**Comment by victorolinasc** [comment]
@deadtrickster I've been having this issue even without opening elixir-mode on current master of Emacs. Are you also having this issue outside elixir? I too think is a regex bug on Emacs ...

**Comment by deadtrickster** [comment]
nope, i don't. but i use handful of modes anyways.

**Comment by nykma** [comment]
Also experienced the "complete freeze" here.
After some profiling, I found that `font-lock-fontify-keywords-region` takes a huge mount of CPU.
Maybe it's also related to this case?

**Comment by jsmestad** [comment]
I think I am hitting this as well. At first I thought it was due to lsp-mode (even went as far to report a false bug at emacs-lsp/lsp-mode#1143). I want to link it here so others can track this issue.

**Comment by jsmestad** [comment]
@deadtrickster has that patch been working for you? It may be worth pushing it in as a PR.

**Comment by dgutov** [comment]
I just opened #448 which contains a more comprehensive cleanup, and a good explanation. Please check it out, everyone.
