### ISSUE TITLE
.exs file issue with Emacs 27, auto-composition-mode enabled

### ISSUE THREAD

**Issue by jsmestad** [elixir-editors/emacs-elixir#447]
## Background

I have been having issues with Emacs 27.x and opening `config/*.exs` files on my Elixir projects. It causes the editor to completely lock up where `USR2` signals and `C-g` do nothing to remedy the situation.

## Workaround

I came across [this issue on spacemacs](https://github.com/syl20bnr/spacemacs/issues/12123#issuecomment-483269569) where `ediff` crashed with `Fira Code` or some other ligature-supported font (I am using `Cascadia Code` FYI).

*UPDATE* - I tried using a different font like `Ubuntu Mono` but experienced the same issue. So it does not appear to be ligature or font specific.

Running `(global-auto-composition-mode -1)` before opening the `.exs` file seems to stop the freezing that otherwise happens.

## Unsure the cause

Maybe this is related to #445 and #446 but I cannot be sure.

**Comment by jsmestad** [comment]
Here is a snippet I use to access the `config.exs` files

```elisp
(use-package elixir-mode
  :config
  (progn
    (defun exs-freeze-workaround ()
      (when (and (stringp buffer-file-name)
                 (string-match "\\.exs\\'" buffer-file-name))
        (auto-composition-mode -1)
        (elixir-mode)
        ))
    (add-hook 'elixir-mode-hook
              (if (version<= "27.0" emacs-version) (exs-freeze-workaround))
              (lambda () (add-hook 'before-save-hook 'lsp-format-buffer)))
    ))
```

**Comment by Trevoke** [comment]
Is this actually an issue with elixir-mode or is this an issue with emacs
27.x ?

**Comment by jsmestad** [comment]
@Trevoke I am not 100% sure. I will continue to investigate, but I have only experienced this issue with elixir-mode and `*.exs` files.

Given the issue reported relating to regex using high cpu usage, I think it stands to reason it could be an issue with changes in Emacs 27.x and `elixir-mode`. Any thoughts?

**Comment by victorolinasc** [comment]
@jsmestad can you test again now that #448 is merged?

**Comment by jsmestad** [comment]
@victorolinasc it does not. Updated to latest MELPA and commented out my fix. Same stall as before.

**Comment by jsmestad** [comment]
I do not seem to be hitting this issue, but to be fair it I do not have ligature support enabled via `composition-mode`and I am now on Emacs 28.x.

Closing this issue for now, but if other folks hit the issue, we can re-open.
