### ISSUE TITLE
Remove Python/Ruby dependencies

### ISSUE THREAD

**Issue by victorolinasc** [elixir-editors/emacs-elixir#456]
I believe that the Python/Ruby dependencies on this repo feels a bit awkward. We could either change to Elixir scripts or simple remove them as I don't think they are used anymore.

If you people believe it is okay to remove them I can send a PR.

@axelson @Trevoke @jsmestad

**Comment by jsmestad** [comment]
Yeah I just noticed they are there to be honest.

I think either Elixir, Bash, or ELisp make more sense than Ruby/Python.

**Comment by axelson** [comment]
:+1: for removing those dependencies from me. And I'm agreed with @jsmestad in using bash/elixir/elisp.

**Comment by victorolinasc** [comment]
Nice! 

Do we user those currently? I think they are reminiscent from other maintainers. Currently the "deployment" of the package is merging with master where MELPA is watching to build and provide it.

I think we should really remove them and not switch them to Elixir implementations. 

Is that ok?

**Comment by jsmestad** [comment]
👍

**Comment by axelson** [comment]
Fixed in #457
