### ISSUE TITLE
Better CI pipeline / project tools

### ISSUE THREAD

**Issue by victorolinasc** [elixir-editors/emacs-elixir#458]
Current Emacs package development and its tools for CI pipelines have evolved a lot recently and I think that we could use some updating here to benefit from that.

**WARNING**: I am a complete noob at ELisp package development but someone interested on the subject for a while.

Things I think that could help us here:
- Linters (checkdoc, [relint](https://github.com/mattiase/relint), etc)
- Different test tool not dependent on ert-runner like [buttercup](https://github.com/jorgenschaefer/emacs-buttercup/)
- Alternative package manager / build-tool like [Eldev](https://github.com/doublep/eldev) or [makem.sh](https://github.com/alphapapa/makem.sh)
- Different CI setup/provider like [setup-emacs](https://github.com/purcell/setup-emacs) with GitHub Actions

This issue is to start a, hopefully, health discussion on these matters and try to make this package more active in the meantime. I'll gladly *try* to help implement changes here if they are welcome.

**Comment by axelson** [comment]
I can't speak for everyone but these sound like good changes :+1:

**Comment by Trevoke** [comment]
All of these seem like good things. I'm trying eldev and buttercup, as of today, on a side project of mine. I wasn't aware of setup-emacs but I'll be curious to give it a shot as well.

**Comment by tomekowal** [comment]
Seems like a great idea!
I only had the pleasure to use https://github.com/gonewest818/elisp-lint

**Comment by victorolinasc** [comment]
@Trevoke would love to hear some comments about Eldev... seems like a closer to mix tool than others.

**Comment by jsmestad** [comment]
I had to mess with a bunch of the Travis config in order to get the test matrix passing (see #459). 

I probably butchered it 😞

**Comment by Trevoke** [comment]
## ELDEV

You can see my usage of eldev here: https://github.com/Trevoke/org-gtd.el

The Eldev file looks like:

```elisp
; -*- mode: emacs-lisp; lexical-binding: t; no-byte-compile: t -*-

;; Autodetermined by `eldev init'.
(eldev-use-package-archive 'gnu)
(eldev-use-package-archive 'melpa)

(setq eldev-test-framework 'buttercup)

(eldev-add-extra-dependencies 'test 'with-simulated-input)
```

## BUTTERCUP 

You can see the lone `buttercup` test I have here: https://github.com/Trevoke/org-gtd.el/blob/master/test/org-gtd-test.el

It looks like any BDD style framework - this test doesn't actually have an expectation because it was so much of a pain to get to where it is now but I think i can add one.

## LINTING ET AL.
@tomekowal I don't know anything about elisp-lint, does it connect to package-lint, which is what melpa requests? (not that it's a requirement, it's probably fine if we have our own linting tool and we put it in the build)

https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion

**Comment by tomekowal** [comment]
> I don't know anything about elisp-lint, does it connect to package-lint, which is what melpa requests? (not that it's a requirement, it's probably fine if we have our own linting tool and we put it in the build)

Yes, it does https://github.com/gonewest818/elisp-lint#package-lint

`package-lint` does basic checks to ensure a package is ready for Melpa.
`elisp-lint` does more checks like:
- function declarations
- docs
- indentation
- package-lint

**Comment by Trevoke** [comment]
Addendum - I am using a Github action on my org-gtd package to run the test suite with eldev:

https://github.com/Trevoke/org-gtd.el/blob/master/.github/workflows/test.yml

**Comment by victorolinasc** [comment]
I have the project running with Eldev locally (this is the easy part I guess). Tests run exactly as they are now without issues (except those that are already on the code base like expected failures and so on). 

I plan to:

- [ ] Narrow the support emacs version matrix (more on this below)
- [ ] Try to make the format test that asserts failure not leave a temp file on the system
- [ ] Switch fo GitHub Workflows and [setup-emacs](https://github.com/purcell/setup-emacs)

## About Emacs version support

We have a single test failing in emacs 24.5 which is quite odd to only fail on that version. We have [a hack for Emacs 24.3](https://github.com/elixir-editors/emacs-elixir/blob/01b332495d3f44addeb236428041c4ffa0c2ca3b/elixir-smie.el#L37-L47) because of a bug in SMIE on that version.

I'd like to make a policy here about the versions we will support going on. The Elixir + Erlang combo of supported versions seems like very "aggresive". They usually target only the last 2 major versions. Current we support Emacs 24+ which I think is a somewhat old version by today's standard. 24.1 was release on 2012-06-10 while 25.1 on 2016-09-17. 

There is no strong reason for us to deprecate support for Emacs 24 besides it being old and a bit buggier than newer versions. What I think we could do is to test only 25.1+ on CI  from now on and leave the support for 24 as non-official. Hopefully all LTS distros out there have at least Emacs 25+ and version 24 would be as used as older Emacs versions in terms of percentage. 

Hopefully this is not way too flawed of an argument. I think most packages are going with this strategy anyway. There will always be GIT history for those with older versions too as an option.

If that is okay I'll include that on this next PR

**Comment by victorolinasc** [comment]
Also, running the `eldev lint` command pops up hundreds of issues currently :) I guess this is expected and we can work on them progressively...

**Comment by axelson** [comment]
I am on board with dropping official support for Emacs 24, and your other planned improvements sound great :+1:

**Comment by victorolinasc** [comment]
Things here are done for now! Thanks all for your kind contributions!
