### ISSUE TITLE
tree-sitter support

### ISSUE THREAD

**Issue by wingyplus** [elixir-editors/emacs-elixir#494]
In upcoming emacs (29) they start supporting tree-sitter natively (not a separate package). It would be great if we supporting it. We already have tree-sitter-elixir https://github.com/elixir-lang/tree-sitter-elixir. And have someone already explore on tree-sitter emacs https://github.com/elixir-lang/tree-sitter-elixir/issues/4#issuecomment-1280030796.

**Comment by wkirschbaum** [comment]
@victorolinasc elixir-ts-mode is already in core emacs, but only for 30. I actually started maintaining the mode on emacs core as an upstream.. I am also strongly considering adding a lightweight elixir-mode to core emacs later this year... but need to think about how and what this might mean. 

elixir-ts-mode is in most popular support packages as well and should just work out of the box ( please log a bug if i missed one ).

**Comment by wkirschbaum** [comment]
the idea is to get elixir work as close to out of the box as possible with emacs with stable features, then have perhaps this or another package with fancier stuff. 🤷🏻. i have a elixir-compile-mode i want to add somewhere, but not sure where yet.

**Comment by wkirschbaum** [comment]
And I had some fun yesterday with Mitchell adding the credo language server to lsp-mode: https://github.com/emacs-lsp/lsp-mode/pull/4068

**Comment by victorolinasc** [comment]
That is awesome @wkirschbaum ! Thanks a lot for your work here :) I've been using elixir-ts-mode and it is shining. Much appreciated work here :)

I think we should, then, open an issue discussing a vision for Elixir in Emacs from here on out. My guess is that we think a bit alike here but it would be great to collect more feedback on how we should organize things in several projects.

It was suggested before to have a package that would:
- add mix project awareness (how to detect if in a project, in an umbrella and so on)
- add mix tasks calling
- add exunit integration
- add some specialized buffers (like xref, eprof and so on would be nice)
- etc...

Wdyt? We should re-up #465 there with a comment :)

**Comment by wkirschbaum** [comment]
@victorolinasc happy people are using it, lots to do still. specialized buffers would be nice.

**Comment by victorolinasc** [comment]
I will be closing this issue for now. We might change the readme to reflect things discussed here. If anyone wants to write and open a PR it would be greatly appreciated.
