### ISSUE TITLE
Comments in multi-line statements are not handled correctly

### ISSUE THREAD

**Issue by antifuchs** [elixir-editors/emacs-elixir#5]
Lines with to-end-of-the-line comments can sometimes cause the nested lexer to go wild & scan to the end of the buffer for the next token. Examples in the `indents-continuation-lines-with-comments` test.

Examples:

``` ruby
  def foo do #bla
            oh_noes    
  end
```

``` ruby
    write_env_tmp_dir('TMPDIR') || # foo
                                  write_env_tmp_dir('TEMP')  ||
                                  write_env_tmp_dir('TMP') ||
                                  write_tmp_dir("/tmp")     ||
                                  ((cwd = cwd()) && write_tmp_dir(cwd))
```

**Comment by v6** [comment]
// , Why does Elixir not have multi-line comments, in the first place, though?

**Comment by tonini** [comment]
@v6 This have nothing to do with the emacs-elixir in particular. 

In Elixir you just stack your comments, there is no need for a multi-line specific syntax

**Comment by v6** [comment]
// , Consider WHY someone would want a multi-line comment. 

Anything come to mind? Any good reasons?
